### ISSUE TITLE
Forgot password functionality with email for registered users

### ISSUE THREAD

**Issue by Pythonian** [zuri-training/Col_Films_Proj_Team_113#17]
**Description**

Registered users may have forgotten the password used when registering their account. This feature will enable registered users to provide the email address they registered with so that a verification link will be sent to their email which they can use to create a new password.

**Tasks**

- [ ] Password reset
- [ ] Password reset done
- [ ] Password reset confirm
- [ ] Password reset complete

**Guide**

* Make use of django built-in authentication for the heavy lifting of this feature
* Use internalization to translate strings where necessary

_Please make use of the comment section for clarifications or add more tasks to be done._
