### ISSUE TITLE
Fix the user account (authentication) app

### ISSUE THREAD

**Issue by Pythonian** [zuri-training/Col_Films_Proj_Team_113#79]
**Tasks**

- [ ] Login
- [ ] Sign up
- [ ] Sign up verification
- [ ] Forgot password with email and phone number
- [ ] Write some Tests
